"""empty message

Revision ID: c94d14d92c44
Revises: 
Create Date: 2023-11-18 13:30:59.712684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94d14d92c44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_user_account'), ['account'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_user_account'))

    op.drop_table('tb_user')
    # ### end Alembic commands ###
