"""empty message

Revision ID: cb406086f0d5
Revises: c94d14d92c44
Create Date: 2023-11-18 14:26:18.335469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb406086f0d5'
down_revision = 'c94d14d92c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_account'), ['account'], unique=True)

    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_index('ix_tb_user_account')

    op.drop_table('tb_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account', sa.VARCHAR(length=30), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.create_index('ix_tb_user_account', ['account'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_account'))

    op.drop_table('User')
    # ### end Alembic commands ###
